Feature/ja 54 schedule item controller
infoshareacademy/jcszr12-Jaszczur pull request #31
Opened 2024-02-29 18:13 UTC by skrawus

Create schedule item controller

I created a controller and views for schedule-item. Merged develop into the branch and tested it. Names are left as they are at default so we can agree on the names later. There is also a new navigation link added in _Layout.cshtml only for tests.

2024-03-01 07:31 UTC, Zjyslav reviewed
Aside from the two comments I had in code:
- Add the same check for null object as in `Details` to `Edit` and `Delete`
- Remove `Id` field from create View - it's not passed to `_dataAccess` anyway, so setting it creates false expectations.

2024-03-01 07:31 UTC, Zjyslav commented on TutorLizard.Web/Controllers/ScheduleItemController.cs
> +                return RedirectToAction("Error");
We don't have `Error` action in this controller. I get 404. Maybe let's redirect to Index.

2024-03-01 07:31 UTC, Zjyslav commented on TutorLizard.Web/Controllers/ScheduleItemController.cs
> +                return View(_dataAccess.GetAllScheduleItems());
This view expects single ScheduleItem. You can simply give it `model`.

2024-03-01 08:27 UTC, Zjyslav requested changes
My previous comments were supposed to be request changes.

2024-03-01 09:42 UTC, skrawus commented
Ok, thanks. I've added the null checks but I'm wondering about this part of your comment:
"Remove `Id` field from create View". There is only AdId and I think we should pass it, as the `scheduleItemRequest` has to be attached to a specific ad

2024-03-01 14:39 UTC, Zjyslav commented
> Ok, thanks. I've added the null checks but I'm wondering about this part of your comment: "Remove `Id` field from create View". There is only AdId and I think we should pass it, as the `scheduleItemRequest` has to be attached to a specific ad

We need `AdId`, we don't need `Id`.
Notice that when you process the creation, you call `_dataAccess.CreateScheduleItem(adId, dateTime);`, so if only these 2 field are used, why ask user to provide anything else?

2024-03-01 17:15 UTC, skrawus commented
Got it! Corrected

2024-03-01 19:42 UTC, Zjyslav approved these changes
It's good enough and I don't want to hold it back, but you might want to remove `Id` also from Edit view, because even if I try to change it, `Id` stays the same.

2024-03-03 18:50 UTC, Zjyslav approved these changes

2024-03-03 18:59 UTC, merged